name: Daily Stock Data Fetch

on:
  schedule:
    # Run at 9:15 AM ET (13:15 UTC) every weekday
    - cron: '15 13 * * 1-5'
  workflow_dispatch:  # Allow manual triggers for testing

jobs:
  fetch-data:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests
          
      - name: Fetch stock data
        run: python src/data_fetcher.py
          
      - name: Commit and push if there are changes
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add data/historical/
          git commit -m "Update stock data $(date +'%Y-%m-%d')" || exit 0
          git push

      - name: Report Status
        if: always()
        run: |
          if [[ $? == 0 ]]; then
            echo "Data fetch completed successfully"
          else
            echo "Data fetch failed"
          fi
